services:
  - type: web
    name: readwell
    runtime: docker
    plan: free
    region: singapore
    repo: https://github.com/jc-delizo/readwell
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: SHIPPING_FEE
        value: 100
      - key: BOOTSTRAP_ADMIN_EMAIL
        sync: false
